sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - 8
  - 9
cache:
  directories:
  - node_modules

branches:
  only:
    - master

before_script:
- npm install -g @angular/cli
- npm install

script:
  - ng build --prod --aot
  - ng test