sudo: required
dist: trusty
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test
  